# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5837eb795dc3732372908cce73cdc753ea78241f363cfaa41ce742773466df4067d43543d33001d84def13beab92fa3a33fcfd0fd1213b63fdca09030f9e0b6

test:
  secret_key_base: 3be3a6fb4474b0ccbd5145490b84745522013d9e949be6c8aa6b1c535ba2b072f6772c4417647b193cb9a3aed8290689b3102f9a6f69b06811197d766aed7ed9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
